### ISSUE TITLE
Include-matched does not work on HTML reports

### ISSUE THREAD

**Issue by peeter123** [agardiner/csv-diff-report#10]
When settings `--include-matched True`, the not changed columns are not added to the HTML file

If I add `new = d` below this line:
https://github.com/agardiner/csv-diff-report/blob/65e0a44c86140528d0dc675b85ca23c0444beeee/lib/csv-diff-report/html.rb#L163

The output is as expected when adding this line:
![image](https://user-images.githubusercontent.com/1242846/35686126-d6de299c-076b-11e8-892b-548da5484195.png)

Without the line:
![image](https://user-images.githubusercontent.com/1242846/35686184-f6d60d1e-076b-11e8-8345-a149147df62f.png)

**Comment by agardiner** [comment]
Thanks for finding this and supplying the fix!

**Comment by peeter123** [comment]
@agardiner Looks like this didn't make it into the 0.3.5 release for some reason when installing it with 'gem install csv-diff-report'. Could you investigate?

**Comment by agardiner** [comment]
Made a minor tweak to the way the --igclude-matched argument was defined (should have been a flag). Can you try with the latest 0.4.1 release and see if its working now?

**Comment by peeter123** [comment]
Looks like the 0.4.1 release fixed it, thanks!

**Comment by agardiner** [comment]
Great!
