### ISSUE TITLE
UTF-8 not recognized

### ISSUE THREAD

**Issue by minthemiddle** [agardiner/csv-diff-report#11]
When comparing two UTF-8 CSVs, I use `csvdiff one.csv two.csv --encoding utf-8`. The outputted HTML does not render German Umlaute properly: e.g. instead of `ü` you get `Ã¼`.

Example CSV:

`one.csv`:
```csv
Aufgabe
Änderung übernehmen
Übergang planen
```

`two.csv`:
```csv
Aufgabe
Camp-Farbkombi überlegen
Übergang planen
```

**Comment by agardiner** [comment]
I'm unable to reproduce your issue - I've copied the two sample files above, and the HTML diff report is correctly rendering.
