### ISSUE TITLE
Save as xlsx

### ISSUE THREAD

**Issue by broex** [agardiner/csv-diff-report#2]
Hello, first off great tool, works a lot faster then the previous tool I used.
But I have a question, when comparing two CSV's and exporting it to a HTML file it takes about 1 minute to complete a compare of around 40000 records. However when exporting the same compare to XLSX it takes quite a lot longer when there are a lot off differences (maybe 20 minutes). 
Where does this difference come from and is it possible to make the xlsx export faster?

**Comment by agardiner** [comment]
The difference is all in the Axlsx library, used to generate the Excel output - if you compare the source of the two output methods in this gem, you'll see there is little difference.
Axlsx has to do a lot of work to create an Excel file in memory - certainly way more than I need to do when outputting the differences to HTML.

**Comment by broex** [comment]
Thanks for your reply. 
Another question, is it possible to save reports as something other then html or xlsx.
I saw you added support for textoutput, does this work?
I tried to use it but got a lot of errors.

**Comment by agardiner** [comment]
It should do, but I haven't used it as extensively as the other output types. Could you open a new issue with examples of the errors you are seeing?
